// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/JeremyLoy/config"
	"github.com/damejeras/shootout/internal/app"
	"github.com/damejeras/shootout/internal/control"
	"github.com/damejeras/shootout/internal/shootout"
	"github.com/go-redis/redis/v8"
	"log"
)

// Injectors from wire.go:

func InitArbiter(cfg *app.ArbiterConfig) (*control.Arbiter, error) {
	state := shootout.NewState(cfg)
	logger := log.Default()
	client, err := initRedisClient(cfg)
	if err != nil {
		return nil, err
	}
	arbiter := control.NewArbiter(cfg, state, logger, client)
	return arbiter, nil
}

func initRedisClient(cfg *app.ArbiterConfig) (*redis.Client, error) {
	options := initRedisConfig(cfg)
	client := redis.NewClient(options)
	return client, nil
}

// wire.go:

func initConfig() (*app.ArbiterConfig, error) {
	var cfg app.ArbiterConfig
	if err := config.FromEnv().To(&cfg); err != nil {
		return nil, err
	}

	return &cfg, nil
}

func initRedisConfig(cfg *app.ArbiterConfig) *redis.Options {
	return &redis.Options{
		Addr: cfg.RedisAddr,
	}
}
