apiVersion: cowboys.mejeras.lt/v1
kind: Shootout
metadata:
  name: shootout-sample
spec:
  shooters:
    - name: John
      health: 10
      damage: 1
    - name: Bill
      health: 8
      damage: 2
    - name: Sam
      health: 10
      damage: 1
    - name: Peter
      health: 5
      damage: 3
    - name: Philip
      health: 15
      damage: 1